name: Deploy Frontend to GitHub Pages

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy client folder to GitHub Pages
        uses: rayluo/github-pages-overwriter@v1.3
        with:
          source-directory: client
          target-branch: gh-pages
